fixed bundle and jpx problems

diff --git a/jpx/jpx b/jpx/jpx
--- a/jpx/jpx
+++ b/jpx/jpx
@@ -1,9 +1,26 @@
 #!/bin/sh
 curdir="$(pwd)"
-max_traverse=10
+max_traverse=20
 traverse_count=0
 found_package_yml=0
+while [ $traverse_count -lt $max_traverse ]; do
+	if [ -f "$curdir/package.yml" ]; then
+		cd "$curdir"
+		found_package_yml=1
+		break
+	fi
+	parentdir="$(dirname "$curdir")"
+	if [ "$parentdir" = "$curdir" ]; then
+		break
+	fi
+	curdir="$parentdir"
+	traverse_count=$((traverse_count+1))
+done
 
+if [ $found_package_yml -eq 0 ]; then
+	echo "Error: package.yml not found"
+	exit 1
+fi
 if [ $# -eq 0 ]; then
 	echo "Add exec dependencies to your package.yml to make it available to jpx"
 	echo "available commands :"
@@ -13,24 +30,6 @@ if [ $# -eq 0 ]; then
 		fi
 	done
 else
-	while [ $traverse_count -lt $max_traverse ]; do
-		if [ -f "$curdir/package.yml" ]; then
-			cd "$curdir"
-			found_package_yml=1
-			break
-		fi
-		parentdir="$(dirname "$curdir")"
-		if [ "$parentdir" = "$curdir" ]; then
-			break
-		fi
-		curdir="$parentdir"
-		traverse_count=$((traverse_count+1))
-	done
-
-	if [ $found_package_yml -eq 0 ]; then
-		echo "Error: package.yml not found"
-		exit 1
-	fi
 	export PATH="$curdir/jpm_dependencies/execs:$PATH"
 	"$@"
 fi
